name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: make test
      - name: Build release binaries
        run: make dist
      - name: Generate changelog
        id: changelog
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 HEAD^)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "## Changes" >> $GITHUB_OUTPUT
          git log --pretty=format:"* %s" $previous_tag..$latest_tag >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/whook-linux-amd64
            dist/whook-linux-arm64
            dist/whook-darwin-amd64
            dist/whook-darwin-arm64
            dist/whook-windows-amd64.exe
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
