name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Run tests
        run: make test
      - name: Build release binaries
        run: make dist
      - name: Generate checksums
        run: |
          cd dist
          sha256sum whook-* > checksums.txt
      - name: Generate changelog
        id: changelog
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "## Changes" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT

          # Get all commits until this tag
          git log --pretty=format:"* %s" $(git rev-list --max-parents=0 HEAD)..HEAD >> $GITHUB_OUTPUT

          echo "" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "SHA256 Checksums are in checksums.txt" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/whook-linux-amd64
            dist/whook-linux-arm64
            dist/whook-darwin-amd64
            dist/whook-darwin-arm64
            dist/whook-windows-amd64.exe
            dist/checksums.txt
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
